import type { User, Farm, Animal, HealthRecord, Employee } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Abdullah Khan",
    email: "admin@farm.com",
    role: "superadmin",
    status: "active",
  },
  {
    id: "2",
    name: "Waleed Ahmed",
    email: "waleed@farm.com",
    role: "owner",
    farmId: "farm1",
    status: "active",
    phone: "03001234567",
    cnic: "35202-1234567-1",
    contactNumber: "03001234568",
    address: "House 45, Model Town, Lahore",
    ownerId: "OWN-001",
  },
  {
    id: "3",
    name: "Shayan Ali",
    email: "shayan@farm.com",
    role: "executive-manager",
    farmId: "farm1",
    status: "active",
  },
  {
    id: "4",
    name: "Tasmiah Noor",
    email: "tasmiah@farm.com",
    role: "owner",
    farmId: "farm2",
    status: "active",
    phone: "03112345678",
    cnic: "42101-9876543-2",
    contactNumber: "03112345679",
    address: "Plot 12, DHA Phase 6, Karachi",
    ownerId: "OWN-002",
  },
  {
    id: "5",
    name: "Nouman Hassan",
    email: "nouman@farm.com",
    role: "owner",
    farmId: "farm3",
    status: "active",
    phone: "03331122334",
    cnic: "37405-5544332-1",
    contactNumber: "03331122335",
    address: "Street 8, F-10 Markaz, Islamabad",
    ownerId: "OWN-003",
  },
]

export const mockFarms: Farm[] = [
  {
    id: "farm1",
    name: "Al-Baraka Dairy Farm",
    location: "Lahore, Punjab",
    size: 250,
    createdAt: "2023-01-15",
    ownerId: "2",
    totalCows: 150,
    totalActiveCollars: 120,
    totalInactiveCollars: 30,
  },
  {
    id: "farm2",
    name: "Madina Livestock Farm",
    location: "Karachi, Sindh",
    size: 450,
    createdAt: "2022-06-20",
    ownerId: "4",
    totalCows: 300,
    totalActiveCollars: 275,
    totalInactiveCollars: 25,
  },
  {
    id: "farm3",
    name: "Rehmat Cattle Farm",
    location: "Islamabad Capital Territory",
    size: 180,
    createdAt: "2023-05-10",
    ownerId: "5",
    totalCows: 95,
    totalActiveCollars: 80,
    totalInactiveCollars: 15,
  },
]

export const mockAnimals: Animal[] = [
  {
    id: "animal1",
    farmId: "farm1",
    name: "Gulabi",
    type: "cattle",
    age: 5,
    weight: 1200,
    status: "healthy",
    inEstrus: true,
    collarId: "COL-001",
    breed: "Sahiwal",
    currentTemperature: 38.5,
    activityLevel: "normal",
    averageTemperature: 38.3,
  },
  {
    id: "animal2",
    farmId: "farm1",
    name: "Hira",
    type: "cattle",
    age: 3,
    weight: 900,
    status: "healthy",
    inEstrus: false,
    collarId: "COL-002",
    breed: "Holstein Friesian",
    currentTemperature: 38.2,
    activityLevel: "high",
    averageTemperature: 38.4,
  },
  {
    id: "animal3",
    farmId: "farm2",
    name: "Sona",
    type: "cattle",
    age: 4,
    weight: 1100,
    status: "healthy",
    inEstrus: false,
    collarId: "COL-003",
    breed: "Cholistani",
    currentTemperature: 38.8,
    activityLevel: "low",
    averageTemperature: 38.9,
  },
  {
    id: "animal4",
    farmId: "farm3",
    name: "Moti",
    type: "cattle",
    age: 6,
    weight: 1300,
    status: "sick",
    inEstrus: false,
    collarId: "COL-004",
    breed: "Sahiwal",
    currentTemperature: 39.5,
    activityLevel: "low",
    averageTemperature: 38.4,
  },
  {
    id: "animal5",
    farmId: "farm3",
    name: "Neela",
    type: "cattle",
    age: 2,
    weight: 800,
    status: "healthy",
    inEstrus: true,
    collarId: "COL-005",
    breed: "Red Sindhi",
    currentTemperature: 38.3,
    activityLevel: "normal",
    averageTemperature: 38.2,
  },
]

export const mockHealthRecords: HealthRecord[] = [
  {
    id: "health1",
    animalId: "animal1",
    collarId: "COL-001",
    date: "2024-12-01",
    notes: "Regular checkup - animal showing signs of estrus cycle",
    veterinarian: "Dr. Muhammad Asif",
  },
  {
    id: "health2",
    animalId: "animal2",
    collarId: "COL-002",
    date: "2024-11-28",
    notes: "Vaccination completed successfully",
    treatment: "FMD Vaccine",
    veterinarian: "Dr. Ayesha Malik",
  },
  {
    id: "health3",
    animalId: "animal4",
    collarId: "COL-004",
    date: "2024-12-08",
    notes: "High fever detected, showing signs of infection",
    treatment: "Antibiotics prescribed",
    veterinarian: "Dr. Usman Farooq",
  },
  {
    id: "health4",
    animalId: "animal5",
    collarId: "COL-005",
    date: "2024-12-05",
    notes: "Routine health examination - all vitals normal",
    veterinarian: "Dr. Fatima Zehra",
  },
]

export const mockEmployees: Employee[] = [
  {
    id: "emp1",
    farmId: "farm1",
    name: "Shayan Ali",
    email: "shayan@farm.com",
    phone: "03001234567",
    role: "executive-manager",
    joinDate: "2023-03-10",
  },
  {
    id: "emp2",
    farmId: "farm2",
    name: "Hassan Raza",
    email: "hassan@farm.com",
    phone: "03221234567",
    role: "executive-manager",
    joinDate: "2023-06-15",
  },
  {
    id: "emp3",
    farmId: "farm3",
    name: "Bilal Ahmed",
    email: "bilal@farm.com",
    phone: "03451234567",
    role: "executive-manager",
    joinDate: "2023-08-20",
  },
]
